// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 1/15/2026, 9:55:45 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/Users/fabian/dev/Personal/mlops/services/web/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/fabian/dev/Personal/mlops/services/web/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/fabian/dev/Personal/mlops/services/web/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/fabian/dev/Personal/mlops/services/web/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/fabian/dev/Personal/mlops/services/web/plugins/**/*.{js,ts,mjs}","/Users/fabian/dev/Personal/mlops/services/web/composables/**/*.{js,ts,mjs}","/Users/fabian/dev/Personal/mlops/services/web/utils/**/*.{js,ts,mjs}","/Users/fabian/dev/Personal/mlops/services/web/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/fabian/dev/Personal/mlops/services/web/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/fabian/dev/Personal/mlops/services/web/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/fabian/dev/Personal/mlops/services/web/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;