"""initial_schema_final_attempt

Revision ID: a3527a378cdf
Revises: 
Create Date: 2025-06-01 19:41:23.393221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector

# revision identifiers, used by Alembic.
revision: str = 'a3527a378cdf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Ensure pgvector extension is created before tables that might depend on it
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    
    op.create_table('webpage',
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('html', sa.Text(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('main_content', sa.Text(), nullable=True),
    sa.Column('full_text', sa.Text(), nullable=True),
    sa.Column('headers', sa.JSON(), nullable=True),
    sa.Column('meta_tags', sa.JSON(), nullable=True),
    sa.Column('structured_data', sa.JSON(), nullable=True),
    sa.Column('links', sa.JSON(), nullable=True),
    sa.Column('images', sa.JSON(), nullable=True),
    sa.Column('content_language', sa.String(), nullable=True),
    sa.Column('last_modified', sa.DateTime(timezone=True), nullable=True),
    sa.Column('crawled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.PrimaryKeyConstraint('url')
    )
    op.create_index('idx_webpage_content_language', 'webpage', ['content_language'], unique=False)
    op.create_index('idx_webpage_crawled_at', 'webpage', ['crawled_at'], unique=False)
    op.create_index('idx_webpage_embedding', 'webpage', ['embedding'], unique=False, postgresql_using='ivfflat')
    op.create_index('idx_webpage_search_vector', 'webpage', ['search_vector'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_webpage_search_vector', table_name='webpage', postgresql_using='gin')
    op.drop_index('idx_webpage_embedding', table_name='webpage', postgresql_using='ivfflat')
    op.drop_index('idx_webpage_crawled_at', table_name='webpage')
    op.drop_index('idx_webpage_content_language', table_name='webpage')
    op.drop_table('webpage')
    # ### end Alembic commands ### 